const PERMISSIONS = [
    'MANAGE_USERS',
    'MANAGE_RESOURCES',
    'MANAGE_RESOURCE_ATTACHMENTS',
    'MANAGE_RESOURCE_TAGS',
    'MANAGE_TAGS',
    'MANAGE_LOANS',
    'MANAGE_LOAN_ATTACHMENTS'
]

module.exports = {
    PERMISSIONS: PERMISSIONS
}